# getHQSeriesFromCSV -----------------------------------------------------------

#' Get H and Q Series from CSV File
#' 
#' @param srcfile full path to csv file generated by radar probe
#' @param DN DN in mm. Must be one of 150, 300.
#' @param sep column separator. Default: Tabulator "\\t"
#' @param timeFormat format of timestamp. Default: "\%d.\%m.\%Y \%H:\%M"
#' @param hoffset level offset to be subtracted from the measured level in order
#'   to get the level above the flume
#' @param addTimeColumns if TRUE, time columns containing local date and time
#'   are added
#' @param additionalColumns names of additional columns to be imported. One of
#'   c("I_mA", "Battery_V", "DeviceID")
#' @param \dots further arguments passed to readLogger_Ori_MLog, e.g.
#'   \emph{stopOnMissingColumns}
#'
#' @return data frame with columns \emph{BerlinDateTimeNoDST} (no daylight
#'   saving time adjustment!), \emph{Hraw_m} (measured height in m), \emph{H_m }
#'   (corrected height [= measured height minus offset] in m),\emph{Q_L_s}
#'   (calculated discharge in L/s). If \emph{addTimeColumns} is TRUE the columns
#'   \emph{BerlinDateTime} and \emph{UTCOffset} will be added.
#'   
#' @export
#' 
getHQSeriesFromCSV <- function(
  srcfile, DN, sep = "\t", timeFormat = NULL, hoffset = 0.02,
  addTimeColumns = TRUE, additionalColumns = c("I_mA", "Battery_V"), ...
)
{
  if (is.null(timeFormat)) {
    timeFormat <- c("%d.%m.%Y %H:%M:%S", "%d.%m.%Y %H:%M")
  }
  
  myData <- kwb.logger::readLogger_Ori_MLog(srcfile, sep = sep, timeFormat = timeFormat, ...)
  
  if ("Level_cm" %in% names(myData)) {
    myData <- kwb.utils::hsRenameColumns(myData, list(Level_cm = "Hraw_cm"))
  }
  
  if (!"Hraw_m" %in% names(myData)) {
    kwb.utils::checkForMissingColumns(myData, "Hraw_cm")
    
    # convert cm to m and rename column
    myData$Hraw_cm <- myData$Hraw_cm / 100
    myData <- kwb.utils::hsRenameColumns(myData, list(Hraw_cm = "Hraw_m"))
  }
  
  hdat <- data.frame(
    BerlinDateTimeNoDST = myData$myDateTime,
    Hraw_m = myData$Hraw_m,
    stringsAsFactors = FALSE)
  
  if (length(additionalColumns) > 0) {
    hdat <- cbind(hdat, myData[, additionalColumns])
  }
  
  hdat <- correctHandCalculateQ(hdat, hoffset = hoffset, DN = DN)
  
  if (isTRUE(addTimeColumns)) {
    hdat <- insertLocalDateTimeColumns(hdat)
  }
  
  hdat
}

# correctHandCalculateQ --------------------------------------------------------

#' Correct Level with Offset and Calculate Q
#' 
#' @param hdat data frame containing at least a column \emph{Hraw_m}, as e.g.
#'   retrieved by \code{readLogger_Ori_MLog}
#' @param hoffset offset in m to be subtracted from raw levels before the HQ
#'   relationship is applied
#' @param DN DN in mm, must be one of 150, 300
#'
#' @return data frame with additional columns \emph{H_m, Q_L_s}
#' 
correctHandCalculateQ <- function(hdat, hoffset, DN)
{
  hdat$H_m <- hdat$Hraw_m - hoffset
  
  # Set H to 0 for H < 0
  hdat$H_m[hdat$H_m < 0] <- 0
  
  # calculate flow Q from H
  hdat$Q_L_s <- H_to_Q(hdat$H_m, DN)
  
  hdat
}

# H_to_Q -----------------------------------------------------------------------

#' Calculate Q from Height Above flume
#' 
#' Calculates Q from height h above flume as Q = a*H^b with a and be retrieved
#'   from linear regression between log(H) and log(Q) with H and Q values taken
#'   from manufacturer's table
#' 
#' @param H height above flume in m
#' @param DN DN in mm, must be one of 150, 300
#' 
H_to_Q <- function(H, DN)
{
  regressionCoefficients <- .regressionCoefficientsForDN(DN = DN)
  
  regressionCoefficients$a * H^regressionCoefficients$b
}

# Q_to_H -----------------------------------------------------------------------

#' Back-Calculate Height Above Flume From Discharge
#' 
#' back-calculates height H above flume from discharge Q.
#'   Q = a * H^b <=> H = (Q/a)^(1/b) with a and be retrieved from linear
#'   regression between log(H) and log(Q) with H and Q values taken from
#'   manufacturer's table
#' 
#' @param Q discharge Q in height above flume (in which unit?)
#' @param DN DN in mm, must be one of 150, 300
#' 
Q_to_H <- function(Q, DN)
{
  regressionCoefficients <- .regressionCoefficientsForDN(DN = DN)
  
  (Q/regressionCoefficients$a)^(1 / regressionCoefficients$b)
}

# .regressionCoefficientsForDN -------------------------------------------------
.regressionCoefficientsForDN <- function(DN)
{
  if (DN == 150) {
    
    a <- exp(5.653)
    b <- 1.952
    
  } else if (DN == 300) {
    
    a <- 435.61
    b <- 1.9504
    
  } else {
    
    .stopWithNoSuchDN()
  }
  
  list(a = a, b = b)
}

# .stopWithNoSuchDN ------------------------------------------------------------
.stopWithNoSuchDN <- function()
{
  stop("HQ relationship only available for DN = 150 or DN = 300")
}


